#!/bin/env bash

set -e

BOOKGEN_ROOT="$(cd $(dirname "$0")/..; pwd)"
cd "${BOOKGEN_ROOT}"

source script/env.sh

html=()
for f in "${DOCKER_INCLUDE_HTML[@]}"; do
    html+=('-H' "$f")
done

css=()
for f in "${DOCKER_INCLUDE_CSS[@]}"; do
    css+=('--css' "$f")
done

set -x

script/pandoc \
    --standalone \
    --mathjax \
    "${html[@]}" \
    "${css[@]}" \
    --number-sections --top-level-division=part \
    --shift-heading-level-by=1 \
    --toc \
    --metadata-file src/metadata.yaml \
    --highlight-style="${BOOKGEN_HIGHLIGHT_STYLE}" \
    --from markdown_github+"${BOOKGEN_EXTENSIONS}" \
    --to html5 \
    -o "${DOCKER_OUTPUT_HTML}" \
    "${DOCKER_OUTPUT_MARKDOWN}"
