#!/bin/env bash

set -e

BOOKGEN_ROOT="$(cd $(dirname "$0")/..; pwd)"
cd "${BOOKGEN_ROOT}"

source script/env.sh

set -x

mkdir -p $(dirname "${BOOKGEN_OUTPUT_MARKDOWN}")
script/codebraid codebraid pandoc --overwrite --standalone \
                 --from commonmark_x \
                 --to markdown_github+"${BOOKGEN_EXTENSIONS}" \
                 --metadata-file src/metadata.yaml \
                 -o "${DOCKER_OUTPUT_MARKDOWN}" "${DOCKER_SOURCE[@]}"
