#!/bin/env bash

set -e
shopt -s globstar

BOOKGEN_ROOT="$(cd $(dirname "$0")/..; pwd)"
cd "${BOOKGEN_ROOT}"

source script/env.sh

set -x

rm -rf "${BOOKGEN_OUTPUT_DIR}/includes"
ln -s "${BOOKGEN_INCLUDE_DIR}" "${BOOKGEN_OUTPUT_DIR}/includes"

[ -r "${BOOKGEN_OUTPUT_HTML}" ] || {
    echo '<html><head>' >> "${BOOKGEN_OUTPUT_HTML}"
    for f in "${BOOKGEN_INCLUDE_HTML[@]}"; do
        cat "$f" >> "${BOOKGEN_OUTPUT_HTML}"
    done
    echo '</head><body>generating...</body></html>' >> "${BOOKGEN_OUTPUT_HTML}"
}

URL="http://localhost:${BOOKGEN_PREVIEW_PORT}/${BOOKGEN_OUTPUT_HTML##*/}"
echo 'Running preview server at:'
echo "$URL"
( cd "${BOOKGEN_OUTPUT_DIR}" && PYTHONPATH="${BOOKGEN_ROOT}" python3 -m local.server "${BOOKGEN_PREVIEW_PORT}" 2>/dev/null ) &
PID1="$!"

if which open >/dev/null; then
    open "$URL"
elif which xdg-open >/dev/null; then
    xdg-open "$URL"
fi

mkdir -p bin
GOBIN="$(pwd)/bin" go install github.com/meain/on-change@latest

bin/on-change "${BOOKGEN_SOURCE_DIR}"/**/*.md 'make html' &
PID2="$!"

trap "kill $PID1; kill $PID2" SIGINT

wait
